name: entorno_virtual
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - ansi2html
  - anyio
  - argon2-cffi
  - asttokens
  - async-lru
  - attrs
  - babel
  - beautifulsoup4
  - bleach
  - blinker
  - brotli-python
  - certifi
  - cffi
  - charset-normalizer
  - click
  - colorama
  - comm
  - contourpy
  - cycler
  - dash
  - debugpy
  - decorator
  - defusedxml
  - executing
  - flask
  - flask-compress
  - fonttools
  - h11
  - html5lib
  - httpcore
  - httpx
  - idna
  - importlib-metadata
  - ipykernel
  - ipython
  - ipython_pygments_lexers
  - ipywidgets
  - itsdangerous
  - jedi
  - jinja2
  - joblib
  - json5
  - jsonschema
  - jsonschema-specifications
  - jupyter
  - jupyter-lsp
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - jupyter_events
  - jupyter_server
  - jupyter_server_terminals
  - jupyterlab
  - jupyterlab_pygments
  - jupyterlab_server
  - jupyterlab_widgets
  - kiwisolver
  - markupsafe
  - matplotlib-inline
  - mistune
  - mpmath
  - narwhals
  - nbclient
  - nbconvert
  - nbformat
  - nest-asyncio
  - notebook
  - notebook-shim
  - packaging
  - pandocfilters
  - parso
  - patsy
  - pillow
  - pip
  - platformdirs
  - plotly
  - prometheus_client
  - prompt-toolkit
  - psutil
  - pure_eval
  - pycparser
  - pygments
  - pyparsing
  - pysocks
  - python-dateutil
  - python-fastjsonschema
  - python-json-logger
  - pyyaml
  - pyzmq
  - referencing
  - requests
  - retrying
  - rfc3339-validator
  - rfc3986-validator
  - rpds-py
  - scikit-learn
  - seaborn
  - send2trash
  - six
  - soupsieve
  - sqlite
  - stack_data
  - statsmodels
  - sympy
  - terminado
  - threadpoolctl
  - tinycss2
  - tornado
  - traitlets
  - typing-extensions
  - tzdata
  - urllib3
  - wcwidth
  - webencodings
  - websocket-client
  - werkzeug
  - wheel
  - widgetsnbextension
  - zipp
  - pip:
      - annotated-types==0.7.0
      - dacite==1.9.2
      - filetype==1.2.0
      - imagehash==4.3.2
      - matplotlib==3.10.0
      - minify-html==0.18.1
      - multimethod==1.12
      - networkx==3.6.1
      - numpy==2.1.3
      - pandas==2.2.3
      - phik==0.12.5
      - puremagic==2.2.0
      - pydantic==2.13.4
      - pydantic-core==2.46.4
      - pywavelets==1.9.0
      - scipy==1.14.1
      - setuptools<81
      - tqdm==4.68.2
      - typeguard==4.5.2
      - typing-inspection==0.4.2
      - visions==0.8.1
      - wordcloud==1.9.6
      - ydata-profiling==4.18.4